### ISSUE TITLE
Добавить описание сборки и запуска проекта

### ISSUE THREAD

**Issue by dmitrylebedev** [alexbaumgertner/vk-advanced-search#2]
Было бы здорово сделать краткое описание, как собрать проект.

**Comment by alexbaumgertner** [comment]
Добавил в https://github.com/alexbaumgertner/vk-advanced-search/commit/a10a2645ecfa9b9be5cc35af8d55f5bff8afa9a5, проверь пожалуйста файл https://github.com/alexbaumgertner/vk-advanced-search/blob/master/README.md
